### ISSUE TITLE
Dead icons in nwg-drawer

### ISSUE THREAD

**Issue by Brittle73** [nwg-piotr/nwg-drawer#100]
Hello,

I'm finally coming back around to try and finish configuring and styling my launcher after a bit. I've been reading through the documentation on the entire set of nwg-launchers, as well as just nwg-drawer and -grid and am failing to see anything about how to at least identify the broken apps. Unlike most apps (even if the icon isn't right) where I can hover over the icon and at the bottom of the screen it will tell me what it is, these simply do nothing and say nothing, and I'd really like to get rid of them. I guess they were things pinned to favorites in the past. I'll include a screenshot below so you can see what I am talking about. Aside from going through the entire list of packages and seeing what matches up and what doesn't for .desktop entries vs. pacman -Q output, is there another more efficient way to figure this out specific to this package? Honestly even just resetting the entire thing and starting over would be fine too, but I am also having issues getting pacman to uninstall the packages as well, as it does not list those particular ones. It's been like a year since I started using it and I use your panel and bar too, so I think what I ended up doing was installing the entire launchers or shell package, because I also have nwg-grid and nwg-dmenu installed, along with Azote, nwg-look, and some other packages. Honestly I cannot claim to remember for sure. Any ideas to help me figure this out would be much appreciated, especially regarding where the best place to modify both the style specifically the drawer and if there is a config file that I cannot find that will let me toggle favorites, etc. I know I enabled favorites at some point, but I think I only had the packages individually installed at that point, so I'm afraid I do not remember where I did that. And no, simply right-clicking those does not make them unpin, I manually unpinned all of the favorites just to see if that would clear the field as well. This has been going on for a long time so it doesn't appear to be caused by any other app updates, etc., but I am finally trying to get around to fine tuning the launcher.

It's Monday morning and my coffee hasn't hit the back of my brain yet, so if I left something out sorry, please let me know. I probably did or am confused about how it's packaged. All help is appreciated.

Machine: 
Surface 6 Pro
Arch Linux / Swayfx (all packages updated to latest a few minutes ago via pacman and yay)
Swayfx should be a fully up-to-date fork of normal Sway, swaymsg -v shows:
swaymsg version 0.3.2-19414f6 (Jul 11 2023, branch 'master')

Here is a screenshot of what the broken icons look like when the launcher is pulled up:
![image](https://github.com/nwg-piotr/nwg-drawer/assets/84404407/8299dbfc-182c-4073-8a24-6e3cd9be7d63)

Here are the apps that pacman shows under nwg:
![image](https://github.com/nwg-piotr/nwg-drawer/assets/84404407/ffd0b593-a308-4824-872d-72febaf8e618)

Neofetch in case it has more helpful information:
![image](https://github.com/nwg-piotr/nwg-drawer/assets/84404407/b912e93e-e448-4b29-b3b0-6187a7636b5f)

Please let me know if you need any sort of dump or whatever, and how to pull it for you if you don't mind.

Thank you for your help!

**Comment by nwg-piotr** [comment]
Before we go into further investigation, could you try and remove the `~/.cache/nwg-pin-cache` file? Before you do so, show me the file content.

**Comment by Brittle73** [comment]
> Before we go into further investigation, could you try and remove the `~/.cache/nwg-pin-cache` file? Before you do so, show me the file content.

Okay, I did not know that file existed... or at least must have skipped over it in my reading. Sorry if I did. But that does to appear to have done the job! Thanks!

As requested:
![image](https://github.com/nwg-piotr/nwg-drawer/assets/84404407/1c73992c-7efa-4ea1-be49-5c4fe5b3b45f)
![image](https://github.com/nwg-piotr/nwg-drawer/assets/84404407/c95e888d-49df-4a5b-9719-4ccccf181079)

After being deleted:
![image](https://github.com/nwg-piotr/nwg-drawer/assets/84404407/e9b1511d-8b41-4532-9788-45a1cf936bdf)

And what it looks like now (they're gone!):
![image](https://github.com/nwg-piotr/nwg-drawer/assets/84404407/06c7ab0f-1b31-42c5-87ea-2691aca1857b)

So that's taken care of, thanks! Now... I was having trouble finding the *specific* config and style files for nwg-drawer, not grid, etc. Unless they're the same. Which files would I edit for that, and is there a config file that I can use in the future to modify the contents of the drawer?

Thanks so much! All your stuff is awesome. I need to return to an issue I was having with nwg-panel, but I will go to that thread if it has not been resolved. I also saw it did an update today.

Thanks! Please let me know if any of that looks wonky.

**Comment by nwg-piotr** [comment]
You may also want to get rid of useless entries like "Avahi SSH server", "Avahi VNC Server" and the like. This may be easily done by copying their .desktop files to `~/.local/share/applications/`, and adding the line in each of them:

```text
NoDisplay=true
```

If it comes to config files: nwg-drawer has none. You can only edit the css style sheet, and all the configuration needs to be done via command arguments (See `nwg-drawer -h`). That's because it's intended for use with [nwg-shell](https://nwg-piotr.github.io/nwg-shell), and its config utility.

**Comment by Brittle73** [comment]
Sorry, super late replying to this. Note trying to ghost-post issues :)

Good tip, I'll do that. Does the config utility handle all of your apps as a whole, or can I make changes to specific things like Drawer? Trying to configure opacity, etc.?

No worries if this thread is dead, just figured I'd ask. Thanks!

**Comment by nwg-piotr** [comment]
The config utility uses arguments to talk to the drawer and stuff. All the css styles you can modify freely.
