### ISSUE TITLE
Dotted lines not in drawer.css

### ISSUE THREAD

**Issue by BluishHumility** [nwg-piotr/nwg-drawer#107]
Hi Piotr, sorry if this is kind of a silly issue but I'm trying to figure out how to change these dotted lines to solid lines:

![image](https://github.com/nwg-piotr/nwg-drawer/assets/93340027/75489e52-ff71-4e9c-86a9-558aafb4ad88)

The default `drawer.css` (https://github.com/nwg-piotr/nwg-drawer/blob/main/drawer.css) has dotted line values for `pinned-box` and `files-box`, but it seems these two lines in the screenshot are something else not in the file.

I poked around a bit to try and find any other version of the `drawer.css` which describe more of the options that are being set, but I'll be honest I'm not really sure what I'm looking for. If they can't be changed it's no big deal, I just thought I'd ask before giving up. :smile: 

Thanks for taking a look,
-Jeremy

**Comment by BluishHumility** [comment]
Hi Piotr, thanks for the clue. I did spend some time poking around with this (more than I'd like to admit, actually :smirk:) but wasn't able to get anywhere with the dotted lines. No worries though, like I mentioned it's no big deal--I just wanted to make sure I wasn't missing something. Thanks again for taking a look. :slightly_smiling_face:

**Comment by nwg-piotr** [comment]
I tried as well, and failed too. :)
