### ISSUE TITLE
Can't click on waybar when nwg-drawer is open

### ISSUE THREAD

**Issue by Elu43** [nwg-piotr/nwg-drawer#109]
Hello,

Thank your for your amazing work. I use nwg-drawer with hyprland on arch.

I would like to know how I could keep waybar usable when nwg-drawer is open.

I use waybar with a shortcut to launch nwg-drawer, and I would like to click again to close it (I'm using laptop in tablet mode so no keyboard). But it's impossible to click on any element of waybar when nwg-drawer is open.

I noticed nwg-drawer is not opening as a classic window : no borders, I cannot resize it or move it, so maybe it's the reason.

Best regards

**Comment by nwg-piotr** [comment]
Hi,

The drawer by default opens on the top layer, unless you specify the overlay layer with the `-ovl` argument. You need to check which layer your waybar is placed on.

Also: you can right-click alongside the icons to close the drawer.

**Comment by Elu43** [comment]
I didn't know about that concept of layers. I changed waybar layer to overlay and it works now.
Thank you for your help, sorry to have bothered you.

Best regards

**Comment by nwg-piotr** [comment]
> Thank you for your help, sorry to have bothered you.

You're welcome. For quick Q&A feel free to join the nwg-shell Matrix space.
