### ISSUE TITLE
Issues on touch devices

### ISSUE THREAD

**Issue by AmirDahan** [nwg-piotr/nwg-drawer#110]
When using nwg-drawer on a device with a touchscreen, trying to scroll down will cause the program your finger was on to be launched on release

**Comment by nwg-piotr** [comment]
This will be difficult for me to resolve, as I have no touch screen device atm. I broke the display. :scream:

**Comment by nwg-piotr** [comment]
I wasted a day on trying to fix it, but no success so far.

**Comment by nwg-piotr** [comment]
OK, got it.
