### ISSUE TITLE
feature: power options

### ISSUE THREAD

**Issue by Serpentian** [nwg-piotr/nwg-drawer#111]
It would be great, if we had a way to configure power options, similar way it's done in kde's plasma drawer:

![image](https://github.com/nwg-piotr/nwg-drawer/assets/106916212/e4bbe77a-e8fe-44f1-bf1e-11ffb3a5f500)

**Comment by nwg-piotr** [comment]
Since we don't use a configuration file, the visibility of each button would depend on passing the appropriate command as an argument, e.g.:

`nwg-drawer -sleep 'systemctl suspend' -reboot 'systemctl reboot' -poweroff 'systemctl poweroff'`

right?

**Comment by Serpentian** [comment]
> Since we don't use a configuration file, the visibility of each button would depend on passing the appropriate command as an argument

Sounds great, I'm ok with such solution

**Comment by nwg-piotr** [comment]
I will try to add this feature soon.

**Comment by nwg-piotr** [comment]
This would look something like this (w/ all the power commands):

![image](https://github.com/nwg-piotr/nwg-drawer/assets/20579136/1c3afd8d-d6e1-4838-a08e-1b5edd93f560)

**Comment by nwg-piotr** [comment]
Improved icons:

![image](https://github.com/nwg-piotr/nwg-drawer/assets/20579136/cee744e5-4fcd-4956-bca6-1f5e1782cebf)

**Comment by nwg-piotr** [comment]
Thank you for a good idea.
