### ISSUE TITLE
Use power/reset/exit icons from theme if .svg are unavailable

### ISSUE THREAD

**Issue by NHOrus** [nwg-piotr/nwg-drawer#122]
Due to packaging issues, nwg-drawer in gentoo shows no power/reset/exit/sleep icons.
It would be nice, if svg icons are missing, to pull icon from theme. It also would unify looks of apps and buttons.

**Comment by nwg-piotr** [comment]
Which specific icon names would you like me to use? Remember, that they must exist in Adwaita GTK theme.

**Comment by NHOrus** [comment]
Exit - system-log-out-symbolic.svg
Lock - system-lock-screen-symbolic.svg
Poweroff - system-shutdown-symbolic.svg
Reboot - system-reboot-symbolic.svg
Can't find any for Sleep

**Comment by nwg-piotr** [comment]
> Can't find any for Sleep

Don't stop searching! ;)

**Comment by nwg-piotr** [comment]
Maybe this one?

![dialog-error-symbolic](https://github.com/nwg-piotr/nwg-drawer/assets/20579136/20387ab7-d42a-4ec3-9860-1c94938a1273)

**Comment by nwg-piotr** [comment]
Finally I ended up using the `face-yawn-symbolic` icon, as the above looks differently in themes other than Adwaita (exclamation, mostly). Keep in mind that it still won't look well with some icon themes.

![obraz](https://github.com/nwg-piotr/nwg-drawer/assets/20579136/d4d1164d-80d2-4556-abfb-97532d1bfda1)

To use icon theme icons, add the `-pbuseicontheme` flag.

**Comment by NHOrus** [comment]
Thank you
