### ISSUE TITLE
Directories listed on excluded-dirs are not being ignored

### ISSUE THREAD

**Issue by msmafra** [nwg-piotr/nwg-drawer#133]
Hello there.
I'm on 0.4.9 on Fedora 41 Beta. Tried to compile 0.5.1, but couldn't to check it happens with the newest too.
I basically include almost all my user folders inside the excluded-dirs files since I don't use the file search from nwg-drawer, usually I search from inside Nautilus. Also it makes nwg-drawer freeze/stutter a bit when I'm typing the search term. 

```
❯ cat ~/.config/hypr/nwg/excluded-dirs
Documentos
Documents
Downloads
Músicas/
Musicas/
Vídeos/
Videos/
BACKUPS/⏎   
```

**Comment by nwg-piotr** [comment]
As you rightly pointed out in the previous PR, the proper path is `~/.config/nwg-drawer/`.

**Comment by msmafra** [comment]
> As you rightly pointed out in the previous PR, the proper path is `~/.config/nwg-drawer/`.

I forgot o mention that I symlinked to `~/.config/nwg-drawer/` and it finds the file when running nwg-drawer even with the file copied there.

```
❯ cd ~/.config/nwg-drawer/
~/.config/nwg-drawer
 .682ns fsh ❯ cat excluded-dirs
Applications/
BACKUPS/
Documentos/
Downloads/
Games/
Imagens/
Misc/
Modelos/
Músicas/
Projects/
Público/
sshfs/
Streaming/
Vídeos/

❯ nwg-drawer -r
INFO[0000] term: xterm-256color
INFO[0000] lang: pt_BR
INFO[0000] Config dir: /home/coop/.config/nwg-drawer
INFO[0000] Data dir: /usr/share/nwg-drawer
INFO[0000] Found 0 pinned items
INFO[0000] Data dir: /usr/share/nwg-drawer
INFO[0000] Found 203 desktop files
INFO[0000] Skipped 5 duplicates; 88 .desktop entries hidden by "NoDisplay=true"
INFO[0000] Found 6 associations in /home/coop/.config/nwg-drawer/preferred-apps.json
INFO[0000] Found 14 search exclusions in /home/coop/.config/nwg-drawer/excluded-dirs
INFO[0000] Preferring dark theme variants
INFO[0000] Using style from /home/coop/.config/nwg-drawer/drawer.css
INFO[0000] Setting GTK layer shell keyboard mode to default: exclusive
INFO[0000] Using XDG user dirs from /home/coop/.config/user-dirs.dirs
INFO[0000] UI created in 262 ms. Thank you for your patience.
```

![Screenshot-241015_084009](https://github.com/user-attachments/assets/12c028d1-f116-4c59-a82f-8c70723ffb5a)

**Comment by nwg-piotr** [comment]
Try removing trailing slashes.

**Comment by msmafra** [comment]
> Try removing trailing slashes.

The same result. WHen I type steam, for example, it keeps showing results from Documentos, Downloads, Músicas and Imagens. Músicas, for some reason, it just shows the folder not the files or folders that contain the searched term.

![Screenshot-241015_100244](https://github.com/user-attachments/assets/adf6ea11-820d-44cb-8d35-58528aa8b651)

**Comment by nwg-piotr** [comment]
Sorry, no idea. It just works on my side.

**Comment by msmafra** [comment]
I'll use the -nofs parameter, instead of filtering.
