### ISSUE TITLE
is there a style (css) for the math resul label?

### ISSUE THREAD

**Issue by msmafra** [nwg-piotr/nwg-drawer#134]
Is there a style (css) for the math result label?

**Comment by nwg-piotr** [comment]
No. I didn't want to make current users add it tho their style sheets.

**Comment by msmafra** [comment]
Oh, thanks. I just wanted to make it bigger.

**Comment by nwg-piotr** [comment]
I could assign the result label to a CSS ID:

```go
lbl.SetProperty("name", "math-result")
```
Then you'd be able to set the font attributes e.g. like this:

```css
#math-sesult {
    font-size: 16px
}
```

**Comment by msmafra** [comment]
Oh, that would be awesome!

**Comment by msmafra** [comment]
Thank you kindly.
