### ISSUE TITLE
Quite a size jump from 0.4.9 and 0.5.0 to 0.5.1 and 0.5.2

### ISSUE THREAD

**Issue by msmafra** [nwg-piotr/nwg-drawer#135]
Hello there,

Just to check if there is something missing while I'm building 0.5.1 and 0.5.2 locally or if it's just related to the calc functionally that was added, because it's quite a big jump in size from 0.4.9 and 0.5.0 to 0.5.1 and 0.5.2.

![Screenshot-241026_092303](https://github.com/user-attachments/assets/0396d936-8454-4e9f-a23f-0a470e8fa8eb)
In the image I'm replacing 0.4.9 (installed via dnf) with 0.5.2 tha I built locally.

**Comment by nwg-piotr** [comment]
On Arch it's safe, dunno about Fedora.

**Comment by msmafra** [comment]
Actually the size is what got my attention. On my system it is already replace by the sudo make install. That capture was when I was copying to a test system to not have to build it there too.

**Comment by nwg-piotr** [comment]
Sine two releases ago we use one more library.
