### ISSUE TITLE
[Bug] drawer not displaying "theme?" correctly anymore, except if started from the terminal

### ISSUE THREAD

**Issue by hecto600** [nwg-piotr/nwg-drawer#136]
Noticed yesterday the drawer with hard to read text [^1]
Then I tried to change the theme opening `nwg settings` **from the drawer** and noticed the dark theme isn't applied on the panel[^2]
If I open `nwg-shell-config` from the terminal the normal behavior happens[^3]
The same happens with nwg-drawer itself [^4]

[^1]:![swappy-2024-11-01_091959](https://github.com/user-attachments/assets/4e1af8d4-6909-431d-aa68-312e14d087e7)
[^2]:![swappy-2024-11-01_093548](https://github.com/user-attachments/assets/e4b286f4-c595-47e5-861a-4deadea008a7)
[^3]:![swappy-2024-11-01_093829](https://github.com/user-attachments/assets/14fa63b7-77c8-4c5e-9828-e5c057d505c6)
[^4]:![swappy-2024-11-01_102709](https://github.com/user-attachments/assets/1e2e6c04-17a6-4e14-ab13-3a7a8d9f143a)

**Comment by nwg-piotr** [comment]
Looks as if you selected Adwaita in nwg-shell-config -> profile-name -> App drawer -> GTK theme, did you?

![obraz](https://github.com/user-attachments/assets/d7abd529-ed85-4309-97b5-15de16cfd562)

**Comment by hecto600** [comment]
The option was blank. After selecting adwaita, the drawer interface is back to normal. I don't know if I changed this setting but worth to mention scrolling with the mouse wheel could  change options unintentionally. Noticed myself couple of times undoing the configuration I accidentally made.
