### ISSUE TITLE
$mod key launches  nwg-drawer

### ISSUE THREAD

**Issue by rodneylg** [nwg-piotr/nwg-drawer#144]
By itself, pressing the $mod key launchers nwg-drawer.  I can't figure out where in the config files to change this setting.  It's highly annoying, as $mod is used in just about every other keybinding.  So it launches even when I don't want it to.

**Comment by nwg-piotr** [comment]
In nwg-shell-config select the App drawer tab, uncheck this box:

![obraz](https://github.com/user-attachments/assets/4402b8d5-c6ec-45a2-a471-584eaade6282)
