### ISSUE TITLE
Close nwg-drawer if the command `pkill -USR1 nwg-drawer` is called and nwg-drawer is open

### ISSUE THREAD

**Issue by gouvinb** [nwg-piotr/nwg-drawer#31]
# Description
Add a pattern to close nwg-drawer if the command `pkill -USR1 nwg-drawer` is called and nwg-drawer is open.

# Actual result

## In background:

- Launch `nwg-drawer -r`

## In foreground

- Press the shortcut for run `pkill -USR1 nwg-drawer`
- nwg-drawer is displayed
- Press the shortcut for run `pkill -USR1 nwg-drawer`
- This has no effect

# Expected result

## In background:

- Launch `nwg-drawer -r`

## In foreground

- Press the shortcut for run `pkill -USR1 nwg-drawer`
- open nwg-drawer
- Press the shortcut for run `pkill -USR1 nwg-drawer`
- close nwg-drawer

**Comment by nwg-piotr** [comment]
Yes, I thought it should had been done this way right after releasing v0.2.0 :) I'll take a closer look at it tonight.
