### ISSUE TITLE
Allow specifying settings in a config file

### ISSUE THREAD

**Issue by nightly-brew** [nwg-piotr/nwg-drawer#37]
Hi, would it be possible to specify launch settings in a config file as well?
I think it would be of help in standardizing systemd user units and xdg autostart desktop files.

Ideally, nwg-drawer could try to read something like "$XDG_CONFIG_DIR/nwg-drawer/settings" at startup.
For those use-cases where "-r" is specified, the launched instance could first try to trigger the background one, if it exists (kind of like it already does).
If no background instance is running instead, it just starts as that.

Of course, cli arguments should still have precedence over the config file, to allow overriding the default behaviour when needed.

**Comment by nwg-piotr** [comment]
Well, I wanted to keep it simple, so planned on config files for `nwg-panel` only. It's kinda enough of json to deal with. For now I'd say "no", but it could be considered in future development. At the moment I'm working on integration of all the nwg-shell stuff with a common config GUI, and wouldn't like to focus on other things.

**Comment by nightly-brew** [comment]
Got it, thanks anyway!

**Comment by nightly-brew** [comment]
@nwg-piotr Would it be better to add a "wontfix" label?

**Comment by nwg-piotr** [comment]
This doesn't look kind. :)

**Comment by nightly-brew** [comment]
ok, thanks again :)

**Comment by nwg-piotr** [comment]
You may like the new `nwg-shell-config`. Coming soon in ArchLabs Linux.

![2022-01-03-124540_screenshot](https://user-images.githubusercontent.com/20579136/147927073-0de1a68d-09fc-4332-90ac-639b74be2baf.png)

**Comment by nightly-brew** [comment]
That I certainly do!
As a matter of facts, I already found the ability to configure nwg-panel both through file and ui a wonderful feature.
Having it more integrated with your other programs is great!

On a side note, I'm going to bother you later on nwg-panel with an issue I encountered with sway workspaces, still, thanks man for your work :)

**Comment by nwg-piotr** [comment]
> an issue I encountered with sway workspaces

Probably the same which I discovered last night while testing (I don't use this module in real life) and wanted to fix while at the office. Unfortunately it doesn't appear on my testing laptop, and needs to wait until I'm back home. Feel free to submit. It may makes it easier to fix.
