### ISSUE TITLE
Searching by typing misses keypresses after 0810250b3ad27a850033fd57d1519008f0828cd7

### ISSUE THREAD

**Issue by nightly-brew** [nwg-piotr/nwg-drawer#41]
As per title, this commit seems to introduce some regression on the search-by-typing functionality.

Sometimes keypresses are not registered at all, some other times, after typing one letter, the focus is grabbed by the first available entry.
This causes the second letter to be lost. A third letter is again appended to the input. Rinse and repeat.

I specified the first entry 'cause if there is no entry, the input field doesn't lose focus.

**Comment by nwg-piotr** [comment]
You're right. I had to change the key event from key-press to key-release for Esc key. I shouldn't have done it for other keys. Will fix it, thanks.

**Comment by nightly-brew** [comment]
I cannot find any issue anymore. Thanks for the quick fix!
