### ISSUE TITLE
Styling issue.

### ISSUE THREAD

**Issue by triyan1975** [nwg-piotr/nwg-drawer#44]
Hi! Nice project. My first install on FreeBSD 13, Sway, default css file. What`s wrong?
![screenshot](https://user-images.githubusercontent.com/62560337/149078027-6ccce431-b7e9-4720-bb70-86ee5863b55f.png)

**Comment by nwg-piotr** [comment]
Did you [apply your GTK theme](https://github.com/swaywm/sway/wiki/GTK-3-settings-on-Wayland)?

**Comment by triyan1975** [comment]
Yes, "Adwaita". Gtk applications looks good.

**Comment by nwg-piotr** [comment]
Well, the default `drawer.css` matches dark styles. You need either to edit it to fit your theme, or use another one with the `-s` argument. Or use `Adwaita-dark`, as I do. :)

**Comment by jbeich** [comment]
`Adwaita-dark` is part of `gnome-themes-extra` on Gtk < 4 but `nwg-drawer` is a Gtk3 application, so it may not be installed by default.
```
$ pkg rquery -r FreeBSD %ro gnome-themes-extra | sort -u
misc/lxde-common
x11-themes/materia-gtk-theme
x11/cinnamon
x11/gnome3
```

**Comment by nwg-piotr** [comment]
Possibly, but I don't deliver styles for all occasions, at least as long as this project is a solo flight. Feel free to contribute.

**Comment by triyan1975** [comment]
I modified drawer.css and all is ok!
`window {
    background-color: rgba (36, 47, 79, 0.95);
    color: #eeeeee;
    text-shadow: none;
}

/* search entry */
entry {
    background-color: rgba (0, 0, 0, 0.2);
    color: #eeeeee;
}

button, image {
    background: none;
    border: none;
    box-shadow: none;
    text-shadow: none;
    color: #eeeeee;
}

button:hover, button:focus {
    background-color: rgba (255, 255, 255, 0.1);
}

/* in case you wanted to give category buttons a different look */
#category-button {
    margin: 0 10px 0 10px;
}

#pinned-box {
    padding-bottom: 5px;
    border-bottom: 1px dotted gray;
}

#files-box {
    padding: 5px;
    border: 1px dotted gray;
    border-radius: 15px;
}
`
![screenshot](https://user-images.githubusercontent.com/62560337/149615702-2c960308-0267-448d-a61b-7e4e00c84c00.png)

**Comment by nwg-piotr** [comment]
Excellent! This file could be added a sample `drawer-light.css`.
