### ISSUE TITLE
[REQUEST] add window margin

### ISSUE THREAD

**Issue by snehrbass** [nwg-piotr/nwg-drawer#49]
![image](https://user-images.githubusercontent.com/62710600/152602096-99a30519-7441-420f-b8d8-7863131a6b3b.png)

I would like to configure nwg-drawer to look like it's coming out of the top of my screen. However, I see no way to change the margin of the window. Just as an example of implementation, `swaync` solved this by adding `"control-center-margin-bottom"` and others to an additional config.json.

Also, If this is not a feature of interest, how would I allow nwg-drawer to cover my bar (waybar)?

**Comment by snehrbass** [comment]
looking at nwg-menu it would be an attional command line argument.

**Comment by nwg-piotr** [comment]
> how would I allow nwg-drawer to cover my bar

`nwg-drawer -ovl`

If it comes to the margins: I'll add arguments soon.
