### ISSUE TITLE
Blank Icon on Pinned bar, Can't be Removed What-so-ever

### ISSUE THREAD

**Issue by stampixel** [nwg-piotr/nwg-drawer#59]
There is a blank app on my pinned bar. I do not see this app in my "All applications". This happend when I installed Terraria twice by accident the other day. I pinned both of the Tarraria's .desktop icons to the pinned bar, then I noticed that there was two. So I uninstalled 1 of the apps, and their .desktop file, but for some reason, the pinned icon was still there, I tried right clicking it to unpin, it doesn't work. I tried reinstalling nwg-drawer, doesn't work. I also tried completly removing the /usr/share/application folder, all my icons were gone except the pinned blank icon.

Also installed nwg-menu, the blank icon is there.

![IMG_20220326_090319](https://user-images.githubusercontent.com/76885740/160240834-9f379596-01d0-4e16-8e38-c0f8dfda06a3.jpg)

Here are my Specs
```
                                                   stampixel@overdose
                     .%;888:8898898:               ------------------
                   x;XxXB%89b8:b8%b88:             OS: Garuda Linux x86_64
                .8Xxd                8X:.          Host: ASUSTeK COMPUTER INC. UX434FAC
              .8Xx;                    8x:.        Kernel: 5.16.16-zen1-1-zen
            .tt8x          .d            x88;      Uptime: 41 mins
         .@8x8;          .db:              xx@;    Packages: 1346 (pacman)
       ,tSXX°          .bbbbbbbbbbbbbbbbbbbB8x@;   Shell: bash 5.1.16
     .SXxx            bBBBBBBBBBBBBBBBBBBBbSBX8;   Resolution: 1920x1080, 1080x2160
   ,888S                                     pd!   WM: sway
  8X88/                                       q    Theme: Nordic-darker [GTK2/3]
  GBB.                                             Icons: Tela-circle-dark [GTK2/3]
   x%88        d888@8@X@X@X88X@@XX@@X@8@X.         Terminal: alacritty
     dxXd    dB8b8b8B8B08bB88b998888b88x.          Terminal Font: JetbrainsMonoNL
      dxx8o                      .@@;.             CPU: Intel i5-10210U (8) @ 4.200GHz
        dx88                   .t@x.               GPU: Intel CometLake-U GT2 [UHD Graphi
          d:SS@8ba89aa67a853Sxxad.                 Memory: 5088MiB / 7746MiB
            .d988999889889899dd.

```

Message I get if i open it from nwg-menu (Since nwg-drawer doesn't do anything in the terminal if I open it)
```
lang: en_CA
Found 126 desktop files
Skipped 0 duplicates; 26 .desktop entries hidden by "NoDisplay=true"
Using style from /home/stampixel/.config/nwg-panel/menu-start.css
Using XDG user dirs from /home/stampixel/.config/user-dirs.dirs

** (nwg-menu:7287): WARNING **: 09:39:07.966: gtk-layer-shell v0.7.0 may not work on GTK v3.24.33. If you experience crashes, check https://github.com/wmww/gtk-layer-shell/blob/master/compatibility.md
UI created in 108 ms. Thanks for watching.
env vars: []; command: ''; args: []
```

Edit: I counted 100 icons in the "All application" (not including blank icon in pinned bar), so 126 icons minus 26 that are "NoDisplay" equals 100. So the logs are right.

**Comment by nwg-piotr** [comment]
Quick fix: edit (or remove) `~/.cache/nwg-pin-cache`.

**Comment by stampixel** [comment]
Thank you, I'll keep that in mind next time I run into the same issue!
