### ISSUE TITLE
UI shift on long description

### ISSUE THREAD

**Issue by joezak11** [nwg-piotr/nwg-drawer#61]
When an app with a long description is selected (e.g. ferdi) the UI shifts to the right
![2022-05-02T22:25:17,289946527+02:00](https://user-images.githubusercontent.com/69003115/166321642-9c63e47b-cf42-4c52-b778-0f57fca61662.png)

**Comment by nwg-piotr** [comment]
LOL, I haven't ever seen such a long one. :rofl: Will add a line to trim them.

**Comment by nwg-piotr** [comment]
Done, to be released soon.
