### ISSUE TITLE
-nofs command doesn't disable filesearch

### ISSUE THREAD

**Issue by marcandru** [nwg-piotr/nwg-drawer#66]
In my terminal i ran nwg-drawer -nofs
I then proceeded to type in firefox, which has alot of files in cache.
When i type the r in firefox nwg-drawer slows to a hault trying to get all the files to list, even though I gave the -nofs argument

**Comment by nwg-piotr** [comment]
Make sure you're not using a resident instance. If so, kill it first, and use the `-nofs` argument while running nwg-drawer again.
