### ISSUE TITLE
Cannot run on Raspberry Pi (arm64)

### ISSUE THREAD

**Issue by Sunderland93** [nwg-piotr/nwg-drawer#67]
Hello. Running nwg-drawer on Ubuntu Arm 64 (on Raspberry Pi) gives an error:

`cannot execute binary file: Exec format error`

Is nwg-drawer x86-only?

**Comment by nwg-piotr** [comment]
You need to build it for the arm architecture. I only provide x86_64 binary, as I can't test arm builds, having no arm device.

**Comment by Sunderland93** [comment]
Ah, sorry, this is my fault. I build the package incorrectly

**Comment by Sunderland93** [comment]
Works great on Rpi

**Comment by nwg-piotr** [comment]
Wish I had a bigger desk. ;) I've always been curious about this hardware, but I really don't have room anymore.
