### ISSUE TITLE
[CHANGED BEHAVIOR] New installation opens default list differently, can't fix

### ISSUE THREAD

**Issue by xi-pinmping** [nwg-piotr/nwg-drawer#72]
This is less a glitch or bug I believe but my hard drive recently failed and I was without nwg for around a month. Instead of copying a snapshot over I decided to just throw together a whole fresh install. I'm still back with nwg of course lol. But now when I open the drawer, it selects the first icon in the alphabetical list is selected, where previously it selected the first application in my favorited list at the top. Is there a setting I am missing somewhere? I have been looking for any positional options but I haven't seen any yet.

**Comment by nwg-piotr** [comment]
This is expected, and hasn't changed in a very long time. The latest two changes only fixed some bugs, that could cause occasional crashes, and also added support for `Hidden`, `OnlyShowIn` and `NotShowIn`. See latest [releases](https://github.com/nwg-piotr/nwg-drawer/releases), please.

**Comment by xi-pinmping** [comment]
So is there a setting somewhere I am missing to be able to change the default selected app when the drawer opens? I just want to be able to open my browser by only pressing enter after the drawer opens. And sadly it doesn't start with an A lol.

**Comment by nwg-piotr** [comment]
No such setting so far. I'll try to add one it this weekend.

**Comment by xi-pinmping** [comment]
Ah alright, I was digging into releases but sometimes that stuff gets past me so I had to ask. Much appreciated, keep up the great work. I often take a stance against change but have loved a lot of the updates lately.

**Comment by nwg-piotr** [comment]
Thank you. I'll look into what you asked about anyway. Just give me some time. 99% percent of most of the shell components development I do myself. Glorious exceptions are swaync and gtklock.

**Comment by nwg-piotr** [comment]
You were right: it behaved improperly when running as a resident instance.
