### ISSUE TITLE
/tmp/nwg-drawer.lock was owned by other user

### ISSUE THREAD

**Issue by sgse** [nwg-piotr/nwg-drawer#79]
https://forum.garudalinux.org/t/solution-seemingly-random-inability-to-launch-nwg-drawer-launcher-in-sway/25193?u=sgs

Wish everyone a Merry Christmas :-)

**Comment by nwg-piotr** [comment]
Thank you very much, and same to you!

I placed the lock file in `/tmp/`, for it be deleted on restarts, but it possibly it's not a must. I'll try moving it to  `$XDG_DATA_HOME`.
