### ISSUE TITLE
How to add icons to categories?

### ISSUE THREAD

**Issue by bernharl** [nwg-piotr/nwg-drawer#8]
I love this new launcher, a huge improvement to nwggrid! I love the fact that it works with my GTK theme, so I don't need to use hacks to make it work in light mode :)

I see in your screenshots that you have icons for the categories, how do I add those? I'm guessing they should be provided by the GTK theme?

**Comment by nwg-piotr** [comment]
Thank you!

> how do I add those?

During installation, definitions should be copied to `/usr/share/nwg-drawer/desktop-directories`. Icon names are defined in the same way as in .desktop files. See [this folder](https://github.com/nwg-piotr/nwg-drawer/tree/main/desktop-directories). Button images are being set with:

```go
button, _ = gtk.ButtonNewFromIconName(cat.Icon, gtk.ICON_SIZE_MENU)
```

so you should always see an icon, or "image-missing" if name not found. 

Don't you see icons at all? I've just realized, that I didn't set AlwaysShowImage in this place, so you may see no icons if your Gtk theme forces this. Check you `~/.config/gtk-3.0/settings.ini` for the `gtk-button-images` value.

**Comment by bernharl** [comment]
> Don't you see icons at all?

No, just text. I've attached a screenshot. 
![screenshot_2021-07-20_19-41-16_944823315](https://user-images.githubusercontent.com/42568221/126371467-acf1e25e-8ac1-40ad-85b0-c3445068879c.png)



> Check your `~/.config/gtk-3.0/settings.ini` for the `gtk-button-images` value.


I do not have this file at all. I set my gtk theme to breeze-gtk. 
I do have the file `/usr/share/themes/Breeze/settings.ini`, though.
It contains:

```[Settings]
gtk-cursor-theme-name=breeze_cursors
gtk-modules=colorreload-gtk-module
gtk-error-bell=0
```

**Comment by nwg-piotr** [comment]
Will you be able to clone and build from GitHub directly, to check if adding the missing line of code helps?

**Comment by bernharl** [comment]
> Will you be able to clone and build from GitHub directly, to check if adding the missing line of code helps?

Cloning and building from Master works. The icons now show, thank you!
When will you do a new release?

**Comment by nwg-piotr** [comment]
Well, what I'm working on at the moment, won't be finished soon, if at all. I'll release the current Master tonight. You'll need to uninstall what you built, and install the package, of course.

**Comment by bernharl** [comment]
Yeah, I built it into a local directory using DESTDIR anyway :)

**Comment by zhexyez** [comment]
Okay. Now how to remove the icon?) I've commented out `Icon` entry in directory file. Still, there is blank space before the text.

**Comment by nwg-piotr** [comment]
@zhexyez You'd need to edit the code. https://github.com/nwg-piotr/nwg-drawer/blob/433c05ca1eb7f7924ca0549af1ea787ee7f1c344/main.go#L40
