### ISSUE TITLE
Non-ascii character problem in menu name shortening

### ISSUE THREAD

**Issue by milisarge** [nwg-piotr/nwg-drawer#82]
nwg-drawer makes shortening for long names, one of the desktop files looks like below

![resim](https://user-images.githubusercontent.com/15840648/211187502-62aa14c1-391c-40bc-91df-4c33a9b3ef93.png)

Related desktop file name is `Name[tr]=Milis Ekran Görüntüsü`

**Comment by nwg-piotr** [comment]
I'm afraid it's unavoidable in UTF-8 encoding. Your `ü` is actually `&#252;`.

**Comment by milisarge** [comment]
if the character is utf-8 then can't it be trim minus/plus one?

**Comment by nwg-piotr** [comment]
It's not as simple as +/- one. Probably doable, but needs to wait for me to have nothing more urgent to do.

**Comment by nwg-piotr** [comment]
Could you run from the `fix82` branch and tell me if it helps? In Polish it seems to look well.

**Comment by milisarge** [comment]
excellent, Turkish locale don't have a problem either.

**Comment by nwg-piotr** [comment]
Very well. Thanks for confirmation. I'll merge and release today.
