### ISSUE TITLE
Specify icon theme

### ISSUE THREAD

**Issue by 875d** [nwg-piotr/nwg-drawer#84]
I did not understand how I can specify the icon theme, for example to use Papirus

**Comment by nwg-piotr** [comment]
We have the `-g` flag to select the GTK (widgets) theme, but no for the icon theme. At least for now.

**Comment by 875d** [comment]
This got implemented?

**Comment by nwg-piotr** [comment]
Nobody requested so far.

**Comment by 875d** [comment]
I officially request the ability to set a icon theme

**Comment by nwg-piotr** [comment]
Okay, I'll see what I can do this weekend.

**Comment by 875d** [comment]
Looks wonderful. Thanks!

**Comment by nwg-piotr** [comment]
You're welcome. It took 10 minutes. :)
