### ISSUE TITLE
Launching thunar from nwg-drawer opens in sway config directory

### ISSUE THREAD

**Issue by xi-pinmping** [nwg-piotr/nwg-drawer#87]
Issue is fairly straight forward but im not finding anything I could be doing to cause this. I checked my desktop entry for thunar and nothing is out of the ordinary. If I launch from my hotkey it opens in homedir by default, which is expected behavior. Not sure how I can change this problem. 

Keep up the great work, loving everything still!

**Comment by nwg-piotr** [comment]
Haha, no idea! Whenever I start Thunar from, it always opens my home dir first. It looks as if it was started with the `thunar ~/.config/sway` command. The drawer takes commands from .desktop files. Maybe you need to check the line starting from `Exec=` in your `thunar.desktop` file?

**Comment by xi-pinmping** [comment]
The only thunar.desktop file is in my /usr/share/applications directory and the exec line is just `Exec=thunar %U` which is where I get lost lol
