### ISSUE TITLE
Launching certain apps

### ISSUE THREAD

**Issue by matuck** [nwg-piotr/nwg-drawer#97]
When lauching certain apps the the app doesnt launch for excample if I launch gnome-chess it will not launch if loading from sway config use either alt+f1 or the icon on the panel.  If I kill all nwg-drawer applications and launch nwg-drawer from terminal it works as expected.

**Comment by nwg-piotr** [comment]
Sorry, couldn't confirm. Just installed gnome-chess and launched it from nwg-drawer with no issue.

![image](https://github.com/nwg-piotr/nwg-drawer/assets/20579136/1cff8647-c6c1-41f0-878e-3424a36e74e3)

**Comment by matuck** [comment]
This may be a distribution problem.  I am running debian and gnome chess is installed to /usr/games

**Comment by nwg-piotr** [comment]
The drawer takes the exec name (or full path) from the .desktop file. Check your `/usr/share/applications/org.gnome.Chess.desktop` file. 

```text
[Desktop Entry]
(...)
Exec=gnome-chess %U
```
On my side it's just the name, w/o path. This means that the  `gnome-chess` binary location must be included in your `$PATH` environment variable.

Check the binary location:

```text
$ command -v gnome-chess
/usr/bin/gnome-chess
```

And the if it's on your path:

```text
$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```

**Comment by matuck** [comment]
on my side it is just the path gnome-chess as well
```
[Desktop Entry]
(...)
Exec=gnome-chess %U
```
Path for excuteable
```
$ command -v gnome-chess
/usr/games/gnome-chess
```
My path
``` 
$ echo $PATH
/home/matuck/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```
However, if I put a sysmlink from /usr/games/gnome-chess to /usr/local/bin/gnome-chess, it works fine.

**Comment by nwg-piotr** [comment]
Strange. I haven't seen Ubuntu for years. Can't install to check it myself, as I'm on vacation, with an ancient laptop and a slow Internet connection only. :/

**Comment by matuck** [comment]
will keep working at it to see if i find a solution and will post here if i do.

**Comment by nwg-piotr** [comment]
Excellent.

**Comment by matuck** [comment]
looks to be a problem with gdm.  If I stop gdm and login to console then run sway it works fine some something in the way gdm is launching sway

**Comment by nwg-piotr** [comment]
Looks like a step forward. For sway and Hyprland sddm is a decent choice. Or you may just start with `sway` from the command line.

**Comment by matuck** [comment]
Works fine with sddm. Just in case anyone else runs across a similar problem.
